export const ErrorCodes = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_RECENT_AUTH_REQUIRED: "AUTH_RECENT_AUTH_REQUIRED",
  AUTH_INVALID_PROVIDER: "AUTH_INVALID_PROVIDER",
  AUTH_OAUTH2_LOGIN_FAILURE: "AUTH_OAUTH2_LOGIN_FAILURE",
  USER_OAUTH2_ALREADY_LINKED: "USER_OAUTH2_ALREADY_LINKED",
  USER_OAUTH2_ACCOUNT_ALREADY_IN_USE: "USER_OAUTH2_ACCOUNT_ALREADY_IN_USE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
